$(function(){
  $("#home_load").load("html/home_load.html");
});
$(function(){
  $("#footer_load").load("html/footer_load.html");
});
$(function(){
  $("#header_nav_load").load("html/header_nav_load.html");
});
$(function(){
  $("#contact_load").load("html/contact_load.html"); 
});
$(function(){
  $("#mumble_load").load("html/mumble_load.html"); 
});